### ISSUE TITLE
Custom DB Table for users/roles/claims possible different database

### ISSUE THREAD

**Issue by tahirnaveed** [umbraco/UmbracoIdentityExtensions#14]
Any chance, you can give me some pointers to save the user data to a custom tables or to a different database? and not use the default tables...

Thanks

**Comment by Shazwazza** [comment]
I'm not sure if you are posting to the correct repository. What are you referring to? This codebase `UmbracoIdentityExtensions` doesn't store any data, it's just helper methods to interact with Umbraco's Identity implementation. If you are referring to storing Umbraco's own user data elsewhere, that is currently not possible. You should log an issue or feature request on the Umbraco tracker for that: https://issues.umbraco.org
