### ISSUE TITLE
Question: IdentityServer3 or 4 possible

### ISSUE THREAD

**Issue by nigel-dewar** [umbraco/UmbracoIdentityExtensions#18]
Hi there,

Please excuse if this question has already been answered, I am BRAND NEW to the Umbraco community.

My query is, can UmbracoIdentityExtensions be used with IdentityServer3 or 4?, 

And if so, is there any Umbraco sample hooked up with IdentityServer3 or 4 that one can reference?

Cheers

**Comment by nigel-dewar** [comment]
Hi There,

Just a friedly ping to see If I can get an answer on this. Doing some research for work to see how we can use Umbraco

**Comment by Shazwazza** [comment]
Yes it will work but will require some configuration, i unfortunately don't have an example for you. Identity server uses OpenIdConnect so that is the provider you would need to use (similar to the Azure AD one: https://github.com/umbraco/UmbracoIdentityExtensions/blob/master/src/App_Start/UmbracoADAuthExtensions.cs )

**Comment by Shazwazza** [comment]
Might be worth asking on the forum if anyone has hooked this up: https://our.umbraco.org

**Comment by nigel-dewar** [comment]
Cool thanks for this. I can see now what I will need to do.

Should be sweet as hooking it up

Cheers mate.

**Comment by Shazwazza** [comment]
I'd love to ship with an example of that too since it's probably a common provider people will want to use. Let me know how you go.

**Comment by nigel-dewar** [comment]
Thanks mate I certainly will.

and cheers again for the link, that had exactly what I needed to progress

:-)

**Comment by paulsterling** [comment]
@nigel-dewar Just as you asked someone in the community seems to have the answer:

https://yuriburger.net/2017/04/26/login-to-umbraco-backoffice-using-identityserver4/

**Comment by nigel-dewar** [comment]
Oh Sweet thats awesome! Thanks so much for posting on this.

cheers.

**Comment by Shazwazza** [comment]
Nice, though you don't need the `Install-Package UmbracoCms.IdentityExtensions.Microsoft` package, that is for the Microsoft OAuth provider, all you need is `Install-Package UmbracoCms.IdentityExtensions` and then install the package `Microsoft.Owin.Security.OpenIdConnect`

Great post, i'll link to the docs. 

Thanks!
