### ISSUE TITLE
Need to update the Google provider since Google+ is deprecated

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoIdentityExtensions#30]
Microsoft have posted a work around here: https://github.com/aspnet/Announcements/issues/333

We can ship with a snippet for the work around if we stay in Owin 3 but we should really move to Owin 4 when the time comes and the fix will just be part of microsoft's nuget package.

**Comment by wojciech-dabrowski** [comment]
Actually, it is already part of Microsoft NuGet package: https://www.nuget.org/packages/Microsoft.Owin.Security.Google/

**Comment by tommyturkijevic** [comment]
So to make the Google Auth in Umbraco work, all we need to do is update to latest nuget package ?

**Comment by wojciech-dabrowski** [comment]
Not really, current implementation of UmbracoIdentityExtension is working with Owin 3, Microsoft fix is applied to Owin 4. For now, you should implement workaround mentioned here: https://github.com/aspnet/AspNetKatana/issues/251#issuecomment-449587635

**Comment by tommyturkijevic** [comment]
Hi again, But what version of the nuget package do I need 3.0.1.0 ? Or do I need to upgrade this one aswell.

**Comment by wojciech-dabrowski** [comment]
You mean Microsoft.Owin.Security.Google? 3.0.1 should be enough, but it is recommended to update it to the 3.1.0.

**Comment by tommyturkijevic** [comment]
@wojciech-dabrowski Thanks, i had to update to 3.1.0 and the workaround worked perfectly.  Thanks..

**Comment by minheemyung** [comment]
Hello, I'm trying to setup Google authentication, but I'm having an issue below in my local machine. Do you have any idea how to fix this?

Thanks!
Minhee

![image](https://user-images.githubusercontent.com/35103919/59941832-2dd64600-942c-11e9-9861-954d71cb01c3.png)

![image](https://user-images.githubusercontent.com/35103919/59941879-5100f580-942c-11e9-997c-d5b2aa2eb7a9.png)

![image](https://user-images.githubusercontent.com/35103919/59941898-5e1de480-942c-11e9-9570-a32b1771e4c9.png)

**Comment by Shazwazza** [comment]
Closing this, version 2.0.0 requires the latest version of Microsoft.Owin.Security.Google
