### ISSUE TITLE
IdentityExtensions - Umbraco 8 support

### ISSUE THREAD

**Issue by vonbarnekowa** [umbraco/UmbracoIdentityExtensions#31]
Hey,

Will this Nuget be updated to support Umbraco 8? 

Best,
Alec

---
_This item has been added to our backlog [AB#1993](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1993)_

**Comment by peterernst** [comment]
Hi! 
We are also wondering if this will be updated to Umbraco 8? 
Regards/ 
Peter

**Comment by Shazwazza** [comment]
Yes it will, we'll be working on this soon but I currently can't provide you a release date. It won't be a difficult update so a PR would certainly be welcome!

**Comment by vonbarnekowa** [comment]
Hey,

You should mark this issue with the `help-wanted` or `good-first-issue` label.

**Comment by deMD** [comment]
I did make a pull request for Umbraco 8 support last week. Sadly I still get an error which seems to come from the Umbraco Database that I have yet to resolve. Any pair of eyes would be welcome for that!

**Comment by Capellan29** [comment]
Hi, any updates with it?
I really need it working in Umbraco 8

**Comment by vonbarnekowa** [comment]
https://github.com/pralthom/umbraco8-LDAP-auth

**Comment by Capellan29** [comment]
Thanks, I'll test it

**Comment by Capellan29** [comment]
Hi, I'va test this example, but it didn't work for me, I foollowed all the instructions, but I don't know what I'm doing wrong :(

**Comment by vonbarnekowa** [comment]
Can you be more precise? Umbraco version, which error, etc..

**Comment by Capellan29** [comment]
Version -> Umbraco 8.0.2
Error Message -> The server could not be contacted. -> The LDAP server is unavailable.
I can't see in the example where to configure the azureAd:tenantId, azureAd:clientId or azureAd:redirectUrl keys, I thing this should be my error

**Comment by Capellan29** [comment]
Any help?

**Comment by cleversolutions** [comment]
@Shazwazza your right this looks like a simple update. I'll update it for V8 and send a pull request shortly.
