### ISSUE TITLE
Add ability to use this with front end Members

### ISSUE THREAD

**Issue by nickcdev** [umbraco/UmbracoIdentityExtensions#36]
Is it possible to use this to enable Members to log into the front end of the umbraco site with their Google/Facebook account? Then remember their 3rd party account / email in a member profile?

If it is, please could an overview of how to do this be documented?

**Comment by Shazwazza** [comment]
No this is not what this lib is for, this is for the back office only as per readme.

For front-end members you want this: https://github.com/shazwazza/UmbracoIdentity
