### ISSUE TITLE
Azure Active Directory with Easy Auth turned on in Azure

### ISSUE THREAD

**Issue by adamn9** [umbraco/UmbracoIdentityExtensions#41]
Hi Guys! 

I am getting an error when I configured this with the default provided settings; and we are using Umbraco v.8.9.0 

```
 public static class UmbracoADAuthExtensions
  {
        public static void ConfigureBackOfficeAzureActiveDirectoryAuth(this IAppBuilder app, 
            string tenant, string clientId, string postLoginRedirectUri, Guid issuerId,
            string caption = "Active Directory", string style = "btn-microsoft", string icon = "fa-windows")
        {         
            var authority = string.Format(CultureInfo.InvariantCulture,  "https://login.windows.net/{0}",  tenant);
            
var adOptions = new OpenIdConnectAuthenticationOptions
            {
                SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType,
                ClientId = clientId,
                Authority = authority,
                RedirectUri = postLoginRedirectUri
            };

            adOptions.ForUmbracoBackOffice(style, icon);            
            adOptions.Caption = caption;
            adOptions.AuthenticationType = string.Format(
                CultureInfo.InvariantCulture,
                "https://sts.windows.net/{0}/",
                issuerId);

            adOptions.SetBackOfficeExternalLoginProviderOptions(
                new BackOfficeExternalLoginProviderOptions
                {
                    AutoLinkOptions = new ExternalSignInAutoLinkOptions(
                        autoLinkExternalAccount: true),

            
                    DenyLocalLogin = true,

               
                    AutoRedirectLoginToExternalProvider = true
                });

            app.UseOpenIdConnectAuthentication(adOptions);            
        }    

    }

```

Our umbraco is hosted in Azure as an appservice, with the Authentication turned on (stopping anyone external accessing any resources) - the EasyAuth is set to Azure Active Directory too. 
I have tried this with both same registration of Easy Auth and  UmbracoIdentityExtensions and two separate client apps on the same tenant 

When I hit the login page; I simply see "You do not have permission to view this directory or page. "

When I turn off Easy Auth on the App Service, the SSO works. Worth adding we have a config value set for WEBSITE_AUTH_DISABLE_IDENTITY_FLOW as true

**Comment by nul800sebastiaan** [comment]
Hmm, I have not used Easy Auth so I have no idea where to begin, maybe @Shazwazza has a few hints?

**Comment by Shazwazza** [comment]
I haven't looked at that for years but remember investigating years ago and wrote this post, hopefully that helps? https://shazwazza.com/post/getting-umbraco-to-work-with-azure-easy-auth/

**Comment by adamn9** [comment]
Thanks @Shazwazza - I'll try it out and feedback shortly.

**Comment by adamn9** [comment]
Hi Guys, I am afraid that's not worked - any other ideas?
