### ISSUE TITLE
v9 Upgrade

### ISSUE THREAD

**Issue by leehowarth** [umbraco/UmbracoIdentityExtensions#44]
is there currently a plan / timescale for an upgrade of this package to the v9 version of umbraco?

**Comment by Shazwazza** [comment]
This will not be ported to v9, all identity functionality is built in to the cms.

**Comment by cleversolutions** [comment]
Hi @Shazwazza I'm taking the rc out for a spin. I'm wanting to see if I can hook it up to an OAuth2 OIDC service. I think a lot of people might be coming here to see how to do OAuth in v9. Any hints on how one would add an external authentication provider in 9?

Thanks
