### ISSUE TITLE
Extending the ASP.Net Identity implementation for Umbraco "Members" (rather than back office users) 

### ISSUE THREAD

**Issue by terryclancy** [umbraco/UmbracoIdentityExtensions#8]
Hi UmbracoIdentityExtensions Folks,

Can  "UmbracoIdentityExtensions" be used to extend the ASP.Net Identity implementation for Umbraco "Members" (rather than Back Office users) ?  I want to support Facebook etc login for Umbraco "Members".  

If not can you recommend an approach please ?

Thanks

Terry

**Comment by Shazwazza** [comment]
You need to look at this repo: https://github.com/Shazwazza/umbracoidentity

IdentityExtensions is for adding functionality for back office in Umbraco.

**Comment by terryclancy** [comment]
Thanks very much
