### ISSUE TITLE
Where does UmbracoIDentity persist members of the  "IdentityMember" class like PhoneNumber ?

### ISSUE THREAD

**Issue by terryclancy** [umbraco/UmbracoIdentityExtensions#9]
Thanks for your help to date - I now have the basics of UmbracoIdentity working and am working on implementing EmailConfirmation (and will then do FaceBook integration).

I note that UmbracoApplicationMember inherits from UmbracoIdentityMember which inherits from IdentityMember which has several members including for example the string PhoneNumber.

When I include the following code in UmbracoIdentityAccountController.HandleRegisterMember  

            var user = new UmbracoApplicationMember()
            {
                Name = thisUserName,
                UserName = model.UsernameIsEmail || model.Username == null ? model.Email : model.Username,
                Email = model.Email,
                MemberProperties = model.MemberProperties,
                PhoneNumber = "(425)4444490"
            };

I can see the Name and Email stored with the other Member Data in the Umbraco BackOffice - but I do not see the PhoneNumber there.  Why not ?  Is it stored somewhere else or do I need to do something to ensure that other standard members of the ASP.Net Identity "IdentityMember" class are persisted ?

Thanks again for your assistance.

Also  are you in Sydney ? I am an Australian living in Bellevue near Seattle an will be visiting home / Sydney in April and would like to buy you Lunch and/or a beer (a real one - not a virtual one :-) ) if you are available ?

Terry Clancy

ClanceZ

**Comment by Shazwazza** [comment]
Hi, you seem to be posting this question on the wrong github repository. I assume you are looking for UmbracoIdentity (https://github.com/Shazwazza/UmbracoIdentity/) , not IdentityExtensions?

I'm from Sydney but living in Copenhagen, I'll be back closer to the end of 2016 so beers maybe then!

**Comment by terryclancy** [comment]
You are correct - sorry, will repost on UmbracoIdentity ,  also sorry I will miss you in Sydney - I'll let you know if I make it to Copenhagen !!
